### ISSUE TITLE
Werkzeug in Requirements.txt from NeighborlyFrontEnd should be downgraded to work

### ISSUE THREAD

**Issue by ricarfantinelli** [udacity/nd081-c2-Building-and-deploying-cloud-native-applications-from-scratch-project-starter#1]
Werkzeug in Requirements.txt from NeighborlyFrontEnd should be downgraded to work

Instead of 1.0.1 it must be used:

Werkzeug==0.16.0

**Comment by berviantoleo** [comment]
Yes, I'm agree, since `from werkzeug.contrib.atom import AtomFeed` already removed at Werkzeug 1.x.x

**Comment by nayanex** [comment]
Udacity team, please, merge these changes. They are really necessary.

**Comment by SudKul** [comment]
Done in this [commit](https://github.com/udacity/nd081-c2-Building-and-deploying-cloud-native-applications-from-scratch-project-starter/commit/805251d166ad8260ae2135b366021888b8129e7d). Thanks.
